### ISSUE TITLE
Add a demo

### ISSUE THREAD

**Issue by cocowalla** [ovh-ux/ovh-angular-responsive-tabs#4]
Would be nice to see this working without having to build out an Angular app myself

**Comment by antleblanc** [comment]
Hi @cocowalla 

Here you can see how we are using it from [Telecom Control Panel UI](https://github.com/ovh-ux/ovh-manager-telecom) (:telephone_receiver: telephony section) :
https://github.com/ovh-ux/ovh-manager-telecom/blob/master/client/app/telecom/telephony/billingAccount/telecom-telephony-billing-account.html#L23-L67

Another example from [Cloud Control Panel UI](https://github.com/ovh-ux/ovh-manager-cloud) (:cloud: dbaas section):
https://github.com/ovh-ux/ovh-manager-cloud/blob/e574067454334ed0152788312bd89c0b3aa9c1c4/client/app/dbaas/ts/project/details/dbaasts-project-details.html#L5-L38

We'll probably develop a brand new component based on our guidelines from CX department then you shall probably refer here in near future :rocket::
https://github.com/ovh-ux/ovh-ui-angular/tree/master/packages

Hope it's help you :lollipop:.

**Comment by cocowalla** [comment]
Hi, sorry, what I meant was simply a URL to see this component in action?

**Comment by antleblanc** [comment]
Hi,

Here in action with a GIF 🎉 
![responsive-tabs](https://user-images.githubusercontent.com/428384/33145503-e41caf76-cfc0-11e7-8085-a043961c2dfe.gif)

**Comment by cocowalla** [comment]
Perfect, you should add this to the readme!
